### ISSUE TITLE
Seat back to Table View (Bug)

### ISSUE THREAD

**Issue by mlimberg** [jenPlusPlus/eighty-six-systems#50]
If I'm in a specific seat view and click to go back to its parent table, I don't see anything on the dom.

**Comment by jenPlusPlus** [comment]
This was caused by putting linebreaks in my routes/urls. I added the linebreaks to get around linter errors, and the line breaks added 20%s to my urls, causing the routes not to match and the elements not to render

**Comment by jenPlusPlus** [comment]
see https://github.com/jenPlusPlus/eighty-six-systems/pull/52
